//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMantenedor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Precios
    {
        public int PRE_id_pre { get; set; }
        [Display(Name= "Nombre de la Region")]
        public Nullable<int> PRE_id_reg { get; set; }
        [Display(Name ="Id del Peso")]
        public Nullable<int> PRE_id_pes { get; set; }
        [Display(Name ="Precios")]
        public Nullable<decimal> PRE_pre_pre { get; set; }
    
        public virtual Peso Peso { get; set; }
        public virtual Region Region { get; set; }
    }
}
